name: Deploy to Stie
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Site
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd website
          npm ci
      - name: Build website
        run: |
          cd website
          npm run build